classdef SeisObj
    %SeisObj a class definition for storing seismic refraction data.
    %
    % Data fields are W (measured amplitude for each trace), RecLoc- relative
    % geophone locations, NumSamples - the number of data samples in each trace
    % 
    %
    % In this first draft, the object is constructed from a single shot
    % file but the capability to include multiple files for a single shot
    % location could potentially be added on later.
    %
    % Example for generating a seismic object from a single file
    % S = SeisObj('12.dat',1);
    % 
    % There are two data plotting options currently under development:
    %
    % plot(S,'wiggle') or S.plot('will') will create a normalized plot of
    % the seismic wavefoms with time on the y axis and shot offset/geophone
    % number on the x axis. This plot is generated by default for every new
    % seismic object created but this option can be turned off.
    %
    % plot(S,'picks') or S.plot('picks') plots the first arrival pick times
    % and locations.
    %
    % 
    
    properties
        W
        RecLoc
        NumSamples
        SamplingFreq 
        Acquistion_date
        Rec_unit
        Channels
        ShotPosition
        Gain
        LineNumber
    end
         
    properties(Dependent)
        RecXMap_loc
        RecYMap_loc
        ShotXMap_loc
        ShotYMap_loc
        RecTime
    end
    
    properties(SetAccess=private, GetAccess=public)
        Pick_times
        Pick_loc
    end
        
    
    methods
        function newSeisObj = SeisObj(varargin)
            
            filename = varargin{1};
            Number_sources = varargin{2};
            [Amps,FileHeader] = seg2load(filename);
            
            %convert the shot date to a Matlab serial date number
            RecDate = FileHeader.rec.date_rec;
            Rec_Time = FileHeader.rec.time_rec;
            Date = datenum(strcat(RecDate,Rec_Time));
            
            
            if nargin==2 && Number_sources==1;
                newSeisObj.W = Amps;
                newSeisObj.RecLoc = FileHeader.tr.receiver;
                newSeisObj.NumSamples = size(Amps,1);
                newSeisObj.SamplingFreq = FileHeader.tr.sampling;
                newSeisObj.Acquistion_date = Date;
                newSeisObj.Rec_unit = FileHeader.rec.units_rec;
                newSeisObj.Channels =FileHeader.tr.channel;
                newSeisObj.ShotPosition = unique(FileHeader.tr.source);
                newSeisObj.Gain = FileHeader.tr.gain;
                newSeisObj.LineNumber = regexprep(filename,'.dat','');
                
            else
                newSeisObj.W = Amps;
                newSeisObj.RecLoc = FileHeader.tr.receiver;
                newSeisObj.NumSamples = size(Amps,1);
                newSeisObj.SamplingFreq = FileHeader.tr.sampling;
                newSeisObj.Acquistion_date = Date;
                newSeisObj.Rec_unit = FileHeader.rec.units_rec;
                newSeisObj.Channels =FileHeader.tr.channel;
                newSeisObj.ShotPosition = FileHeader.tr.source;
                newSeisObj.Gain = FileHeader.tr.gain;
                newSeisObj.LineNumber = regexprep(filename,'.dat','');
            end
            
            %create a plot of the wiggles for each shot after creating the object
            figure
            wiggle(newSeisObj.W);
                box on;
                set(gca,'YGrid','on')
                tick_locs = get(gca,'YTick');
                set(gca,'YTickLabel',tick_locs* ... 
                    unique(newSeisObj.SamplingFreq)*1e3);
                xlabel('Trace number');
                ylabel('Time (ms)');
                 title({['Record #', num2str(newSeisObj.LineNumber)] ...
                  ['Source Location =', num2str(newSeisObj.ShotPosition)]}, ...
                  'FontWeight','bold');
              
              for i =1:4:size(newSeisObj.W,2);
                  text(i,-20, num2str(newSeisObj.RecLoc(i)-newSeisObj.ShotPosition));
              end
              text(-3,-20,'Offset (m)', 'FontWeight','bold');
        end
        
        %     Calculate the observation times in ms
        function RecTime = get.RecTime(theSeisObj)
            RecTime = (1:theSeisObj.NumSamples)*unique(theSeisObj.SamplingFreq)*1e3;
        end
            
      
        %use ginput to define the first arrival pick locations and times
        function [X,T] = picktimes(theSeisObj)
            
            plot(theSeisObj,'wiggle');
            disp('pick ALL first breaks now, press enter when done')
            [X,T] = ginput;
            X = round(X);
            
        end
        
        %use the picks defined by the picktime
        function Pick_times = get.Pick_times(theSeisObj)
            Pick_times = T*unique(theSeisObj.SamplingFreq)*1e3;
        end
        function Pick_loc = get.Pick_loc(theSeisObj)
                 Pick_loc = theSeisObj.RecLoc(X);
        end
            
            
        %Define some plotting routines for the data
        function plot(theSeisObj,varargin)
            
            if strcmp(varargin,'wiggle')
                figure;
                wiggle(theSeisObj.W);
                box on;
                set(gca,'YGrid','on')
                tick_locs = get(gca,'YTick');
                set(gca,'YTickLabel',tick_locs* ...
                    unique(theSeisObj.SamplingFreq)*1e3);
                xlabel('Trace number');
                ylabel('Time (ms)');
                title({['Record #', num2str(theSeisObj.LineNumber)]; ...
                    ['Source Location =', num2str(theSeisObj.ShotPosition)]}, ...
                    'FontWeight','bold');
                
                for i =1:size(theSeisObj.W,2);
                    text(i,-20, num2str(theSeisObj.RecLoc(i)-theSeisObj.ShotPosition));
                end
                
            elseif strcmp(varargin,'picks')
                figure;
                plot(theSeisObj.Pick_loc,theSeisObj.Pick_time,'bo')
                xlabel('Geophone location')
                ylabel('Pick times (ms)')
                title(['First Arrival Picks for Record #', ...
                    num2str(theSeisObj.LineNumber)], 'FontWeight','bold');
            end
        end
                
      
    end
    
end

